# fly.toml app configuration file generated for discord-bot-9000 on 2025-03-26T14:11:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-bot-9000'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  max_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
